/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions, EventOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { Callback, TransactionObject, ContractEvent } from "./types";

export class IERC20Token extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    balanceOf(arg0: string): TransactionObject<BN>;

    allowance(arg0: string, arg1: string): TransactionObject<BN>;

    transfer(arg0: string, arg1: number | string): TransactionObject<boolean>;

    approve(arg0: string, arg1: number | string): TransactionObject<boolean>;

    transferFrom(
      arg0: string,
      arg1: string,
      arg2: number | string
    ): TransactionObject<boolean>;

    totalSupply(): TransactionObject<BN>;
  };
  events: {
    Transfer: ContractEvent<{
      from: string;
      to: string;
      value: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    Approval: ContractEvent<{
      owner: string;
      spender: string;
      value: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
