/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class MockStableToken extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): MockStableToken;
  methods: {
    _needsRebase(): TransactionObject<boolean>;

    decimals(): TransactionObject<string>;

    _totalSupply(): TransactionObject<string>;

    _targetTotalSupply(): TransactionObject<string>;

    setNeedsRebase(): TransactionObject<void>;

    setTotalSupply(value: number | string): TransactionObject<void>;

    setTargetTotalSupply(value: number | string): TransactionObject<void>;

    mint(arg0: string, arg1: number | string): TransactionObject<boolean>;

    burn(arg0: number | string): TransactionObject<boolean>;

    needsRebase(): TransactionObject<boolean>;

    resetLastRebase(): TransactionObject<void>;

    totalSupply(): TransactionObject<string>;

    targetTotalSupply(): TransactionObject<string>;

    transfer(arg0: string, arg1: number | string): TransactionObject<boolean>;

    transferFrom(
      arg0: string,
      arg1: string,
      arg2: number | string
    ): TransactionObject<boolean>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
