/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions, EventOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { Callback, TransactionObject, ContractEvent } from "./types";

export class SavingsCircle extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    circleMembers(hashedName: string | number[]): TransactionObject<(string)[]>;

    circlesFor(user: string): TransactionObject<(string)[]>;

    circleInfo(
      hashedName: string | number[]
    ): TransactionObject<{
      0: string;
      1: (string)[];
      2: string;
      3: BN;
      4: BN;
    }>;

    balancesForCircle(
      hashedName: string | number[]
    ): TransactionObject<{
      0: (string)[];
      1: (BN)[];
    }>;

    withdrawable(hashedName: string | number[]): TransactionObject<boolean>;

    renounceOwnership(): TransactionObject<void>;

    transferOwnership(newOwner: string): TransactionObject<void>;

    initialize(): TransactionObject<void>;

    addCircle(
      name: string,
      members: (string)[],
      tokenAddress: string,
      depositAmount: number | string
    ): TransactionObject<void>;

    contribute(
      hashedName: string | number[],
      value: number | string
    ): TransactionObject<void>;

    withdraw(hashedName: string | number[]): TransactionObject<void>;

    initialized(): TransactionObject<boolean>;
    owner(): TransactionObject<string>;
    isOwner(): TransactionObject<boolean>;
  };
  events: {
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
